In [ ]:
import torch


In [ ]:
batch_size = 1
seq_len = 3
input_size = 4
hidden_size = 2


In [ ]:
# RNNCell 与 RNN

cell = torch.nn.RNNCell(input_size = input_size, hidden_size = hidden_size)
dataset = torch.randn(seq_len, batch_size, input_size)
hidden = torch.zeros(batch_size, hidden_size)

for ind, data in enumerate(dataset):
    print("=" * 20, ind, "=" * 20)
    print("input_size:", data.shape)

    hidden = cell(data, hidden)
    print("output_size:", hidden.shape)
    print(hidden)

In [ ]:
batch_size = 1
seq_len = 3
input_size = 4
hidden_size = 2
num_layers = 1

cell = torch.nn.RNN(input_size = input_size, hidden_size = hidden_size, num_layers = num_layers)

inputs = torch.randn(seq_len, batch_size, input_size)
hidden = torch.zeros(num_layers, batch_size, hidden_size)

out, hidden = cell(inputs, hidden)

print("outsize:", out.shape)
print("output:", out)
print("hidden_size:", hidden.shape)
print("hidden:", hidden)

In [ ]:
# 序列到序列 seq2seq  使用RNNCell实现
# 通过hello预测ohlol

# 准备数据
idx2char = ["e", "h", "l", "o"]
x_data = [1, 0, 2, 2, 3]
y_data = [3, 1, 2, 3, 2]

one_hot_lookup = [[1, 0, 0, 0],
                  [0, 1, 0, 0],
                  [0, 0, 1, 0],
                  [0, 0, 0, 1]]
            
x_one_hot = [one_hot_lookup[x] for x in x_data]

inputs1 = torch.Tensor(x_one_hot).view(-1, batch_size, input_size)
labels1 = torch.LongTensor(y_data).view(-1, 1)

class Model(torch.nn.Module):
    def __init__(self, input_size, hidden_size, batch_size):
        super(Model, self).__init__()
        self.batch_size = batch_size
        self.input_size = input_size
        self.hidden_size = hidden_size

        self.rnncell = torch.nn.RNNCell(input_size=self.input_size, hidden_size=self.hidden_size)

    def forward(self, inputs, hidden):
        hidden = self.rnncell(inputs, hidden)
        return  hidden

    def init_hidden(self):
        return torch.zeros(self.batch_size, self.hidden_size)

net = Model(input_size, hidden_size, batch_size)

criterion = torch.nn.CrossEntropyLoss()
optmizer = torch.optim.Adam(net.parameters(), lr=0.1)

for epoch in range(15):
    loss = 0
    optmizer.zero_grad()
    hidden = net.init_hidden()
    print("predict string:", end="")
    for inp, label in zip(inputs, labels):
        hidden = net(inp, hidden1)
        loss += criterion(hidden, label)
        _, idx = hidden.max(dim = 1)
        print(idx2char[idx.item()], end="")
    loss.backward()
    optmizer.step()

    print(", epoch [%d15] loss=%.4f" %(epoch + 1, loss.item()))

In [ ]:
# 使用RNN实现

# 准备数据
idx2char = ["e", "h", "l", "o"]
x_data = [1, 0, 2, 2, 3]
y_data = [3, 1, 2, 3, 2]

one_hot_lookup = [[1, 0, 0, 0],
                  [0, 1, 0, 0],
                  [0, 0, 1, 0],
                  [0, 0, 0, 1]]
            
x_one_hot = [one_hot_lookup[x] for x in x_data]

inputs = torch.Tensor(x_one_hot).view(-1, batch_size, input_size)
labels = torch.LongTensor(y_data)

class Model(torch.nn.Module):
    def __init__(self, input_size, hidden_size, batch_size, num_layers):
        super(Model, self).__init__()
        self.num_layers = num_layers
        self.batch_size = batch_size
        self.input_size = input_size
        self.hidden_size = hidden_size

        self.rnn = torch.nn.RNN(input_size=self.input_size, hidden_size=self.hidden_size, num_layers=self.num_layers)

    def forward(self, inputs):
        hidden = torch.zeros(self.num_layers, self.batch_size, self.hidden_size)
        out, _ = self.rnn(inputs, hidden)
        return  out.view(-1, self.hidden_size)


net = Model(input_size, hidden_size, batch_size, num_layers)

criterion = torch.nn.CrossEntropyLoss()
optmizer = torch.optim.Adam(net.parameters(), lr=0.1)

for epoch in range(15):
    loss = 0
    optmizer.zero_grad()
    outputs = net(inputs)
    loss = criterion(hidden, label)
    loss.backward()
    optmizer.step()

    _, idx = outputs.max(dim=1)
    idx = idx.data.numpy()
    print("predict:", "".join([idx2char[x] for x in idx]), end="")
    print(", epoch [%d15] loss=%.4f" %(epoch + 1, loss.item()))

In [3]:
batch_size = 1
seq_len = 3
input_size = 4
hidden_size = 2


In [9]:
# RNNCell 与 RNN

cell = torch.nn.RNNCell(input_size = input_size, hidden_size = hidden_size)
dataset = torch.randn(seq_len, batch_size, input_size)
hidden = torch.zeros(batch_size, hidden_size)

for ind, data in enumerate(dataset):
    print("=" * 20, ind, "=" * 20)
    print("input_size:", data.shape)

    hidden = cell(data, hidden)
    print("output_size:", hidden.shape)
    print(hidden)

==================== 0 ====================
input_size: torch.Size([1, 4])
output_size: torch.Size([1, 2])
tensor([[-0.4566,  0.9857]], grad_fn=<TanhBackward>)
==================== 1 ====================
input_size: torch.Size([1, 4])
output_size: torch.Size([1, 2])
tensor([[-0.5275,  0.9617]], grad_fn=<TanhBackward>)
==================== 2 ====================
input_size: torch.Size([1, 4])
output_size: torch.Size([1, 2])
tensor([[0.7174, 0.8533]], grad_fn=<TanhBackward>)


In [22]:
batch_size = 1
seq_len = 3
input_size = 4
hidden_size = 2
num_layers = 1

cell = torch.nn.RNN(input_size = input_size, hidden_size = hidden_size, num_layers = num_layers)

inputs = torch.randn(seq_len, batch_size, input_size)
hidden = torch.zeros(num_layers, batch_size, hidden_size)

out, hidden = cell(inputs, hidden)

print("outsize:", out.shape)
print("output:", out)
print("hidden_size:", hidden.shape)
print("hidden:", hidden)

outsize: torch.Size([3, 1, 2])
output: tensor([[[ 0.1259,  0.0553]],

        [[-0.9251, -0.0303]],

        [[-0.2819,  0.6459]]], grad_fn=<StackBackward>)
hidden_size: torch.Size([1, 1, 2])
hidden: tensor([[[-0.2819,  0.6459]]], grad_fn=<StackBackward>)


In [44]:
# 序列到序列 seq2seq  使用RNNCell实现
# 通过hello预测ohlol

# 准备数据
idx2char = ["e", "h", "l", "o"]
x_data = [1, 0, 2, 2, 3]
y_data = [3, 1, 2, 3, 2]

one_hot_lookup = [[1, 0, 0, 0],
                  [0, 1, 0, 0],
                  [0, 0, 1, 0],
                  [0, 0, 0, 1]]
            
x_one_hot = [one_hot_lookup[x] for x in x_data]

inputs1 = torch.Tensor(x_one_hot).view(-1, batch_size, input_size)
labels1 = torch.LongTensor(y_data).view(-1, 1)

class Model(torch.nn.Module):
    def __init__(self, input_size, hidden_size, batch_size):
        super(Model, self).__init__()
        self.batch_size = batch_size
        self.input_size = input_size
        self.hidden_size = hidden_size

        self.rnncell = torch.nn.RNNCell(input_size=self.input_size, hidden_size=self.hidden_size)

    def forward(self, inputs, hidden):
        hidden = self.rnncell(inputs, hidden)
        return  hidden

    def init_hidden(self):
        return torch.zeros(self.batch_size, self.hidden_size)

net = Model(input_size, hidden_size, batch_size)

criterion = torch.nn.CrossEntropyLoss()
optmizer = torch.optim.Adam(net.parameters(), lr=0.1)

for epoch in range(15):
    loss = 0
    optmizer.zero_grad()
    hidden = net.init_hidden()
    print("predict string:", end="")
    for inp, label in zip(inputs, labels):
        hidden = net(inp, hidden1)
        loss += criterion(hidden, label)
        _, idx = hidden.max(dim = 1)
        print(idx2char[idx.item()], end="")
    loss.backward()
    optmizer.step()

    print(", epoch [%d15] loss=%.4f" %(epoch + 1, loss.item()))

predict string:

IndexError: Target 3 is out of bounds.

In [46]:
# 使用RNN实现

# 准备数据
idx2char = ["e", "h", "l", "o"]
x_data = [1, 0, 2, 2, 3]
y_data = [3, 1, 2, 3, 2]

one_hot_lookup = [[1, 0, 0, 0],
                  [0, 1, 0, 0],
                  [0, 0, 1, 0],
                  [0, 0, 0, 1]]
            
x_one_hot = [one_hot_lookup[x] for x in x_data]

inputs = torch.Tensor(x_one_hot).view(-1, batch_size, input_size)
labels = torch.LongTensor(y_data)

class Model(torch.nn.Module):
    def __init__(self, input_size, hidden_size, batch_size, num_layers):
        super(Model, self).__init__()
        self.num_layers = num_layers
        self.batch_size = batch_size
        self.input_size = input_size
        self.hidden_size = hidden_size

        self.rnn = torch.nn.RNN(input_size=self.input_size, hidden_size=self.hidden_size, num_layers=self.num_layers)

    def forward(self, inputs):
        hidden = torch.zeros(self.num_layers, self.batch_size, self.hidden_size)
        out, _ = self.rnn(inputs, hidden)
        return  out.view(-1, self.hidden_size)


net = Model(input_size, hidden_size, batch_size, num_layers)

criterion = torch.nn.CrossEntropyLoss()
optmizer = torch.optim.Adam(net.parameters(), lr=0.1)

for epoch in range(15):
    loss = 0
    optmizer.zero_grad()
    outputs = net(inputs)
    loss = criterion(hidden, label)
    loss.backward()
    optmizer.step()

    _, idx = outputs.max(dim=1)
    idx = idx.data.numpy()
    print("predict:", "".join([idx2char[x] for x in idx]), end="")
    print(", epoch [%d15] loss=%.4f" %(epoch + 1, loss.item()))

IndexError: Target 3 is out of bounds.